### ISSUE TITLE
I can't compile the website and deploy it in production

### ISSUE THREAD

**Issue by theG3n15** [Protofy-xyz/Protofy#44]
## Expected Behavior
I should be able to compile the website

## Current Behavior
I run the command "yarn web:build" and a build error appears in the logs. 

## Steps to Reproduce
1. Clone protofy repo
2. Install dependencies
3. Try to run "yarn web:build"

## Context (Environment)
- Default setup
- OS: Windows 11
- Browser: Chrome
- Environment: prod

## Issue demo
![buildBug-webBuild](https://github.com/Protofy-xyz/Protofy/assets/110179160/ad4a0f65-7907-43e0-8a42-f33c709564f9)

**Comment by theG3n15** [comment]
When trying to build in **Ubuntu 20.04**, I encountered this build error related to Expo Constants:

I will add here the complete log: 
```
➤ YN0000: CLI Building entry: ./index.tsx
➤ YN0000: CLI Using tsconfig: tsconfig.json
➤ YN0000: CLI tsup v6.7.0
➤ YN0000: CLI Target: es5
➤ YN0000: ESM Build start
➤ YN0000: TERSER Minifying with Terser
➤ YN0000: TERSER Terser Minification success
➤ YN0000: DTS Build start
➤ YN0000: ESM dist/index.js 170.96 KB
➤ YN0000: ESM ⚡️ Build success in 3682ms
➤ YN0000: DTS ⚡️ Build success in 10015ms
➤ YN0000: DTS dist/index.d.ts 29.84 KB
➤ YN0000: $ npx tsc --baseUrl . --outDir types --rootDir src --emitDeclarationOnly --declarationMap
➤ YN0000: built @my/ui in 7380 ms
➤ YN0000: Done in 21s 363ms
   Skipping validation of types
 ✓ Linting    
   Creating an optimized production build  ..✘ [ERROR] No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4"

    ../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19:
      1 │ import { Platform, uuidv4 } from 'expo-modules-core';
        ╵                    ~~~~~~

✘ [ERROR] No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4"

    ../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19:
      1 │ import { Platform, uuidv4 } from 'expo-modules-core';
        ╵                    ~~~~~~

Error bundling tamagui config: Build failed with 1 error:
../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19: ERROR: No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4" (run with DEBUG=tamagui to see stack)
No bundled config generated, maybe an error in bundling. Set DEBUG=tamagui and re-run to get logs.
   Creating an optimized production build  ...✘ [ERROR] No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4"

    ../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19:
      1 │ import { Platform, uuidv4 } from 'expo-modules-core';
        ╵                    ~~~~~~

Error bundling tamagui config: Build failed with 1 error:
../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19: ERROR: No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4" (run with DEBUG=tamagui to see stack)
No bundled config generated, maybe an error in bundling. Set DEBUG=tamagui and re-run to get logs.
   Creating an optimized production build  .✘ [ERROR] No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4"

    ../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19:
      1 │ import { Platform, uuidv4 } from 'expo-modules-core';
        ╵                    ~~~~~~

   Creating an optimized production build  .✘ [ERROR] No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4"

    ../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19:
      1 │ import { Platform, uuidv4 } from 'expo-modules-core';
        ╵                    ~~~~~~

✘ [ERROR] No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4"

    ../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19:
      1 │ import { Platform, uuidv4 } from 'expo-modules-core';
        ╵                    ~~~~~~

Error bundling tamagui config: Build failed with 1 error:
../../node_modules/expo-constants/build/ExponentConstants.web.js:1:19: ERROR: No matching export in "../../node_modules/expo-modules-core/build/index.js" for import "uuidv4" (run with DEBUG=tamagui to see stack)
No bundled config generated, maybe an error in bundling. Set DEBUG=tamagui and re-run to get logs.
 ⚠ Compiled with warnings

../../node_modules/expo-constants/build/ExponentConstants.web.js
Attempted import error: 'uuidv4' is not exported from 'expo-modules-core' (imported as 'uuidv4').

Import trace for requested module:
../../node_modules/expo-constants/build/ExponentConstants.web.js
../../node_modules/expo-constants/build/Constants.js
../../packages/ui/src/CustomToast.tsx
../../packages/ui/src/index.tsx
../../packages/app/provider/index.tsx

../../node_modules/expo-constants/build/ExponentConstants.web.js
Attempted import error: 'uuidv4' is not exported from 'expo-modules-core' (imported as 'uuidv4').

Import trace for requested module:
../../node_modules/expo-constants/build/ExponentConstants.web.js
../../node_modules/expo-constants/build/Constants.js
../../packages/ui/src/CustomToast.tsx
../../packages/ui/src/index.tsx
../../packages/app/provider/index.tsx

../../node_modules/expo-constants/build/ExponentConstants.web.js
Attempted import error: 'uuidv4' is not exported from 'expo-modules-core' (imported as 'uuidv4').

Import trace for requested module:
../../node_modules/expo-constants/build/ExponentConstants.web.js
../../node_modules/expo-constants/build/Constants.js
../../packages/ui/src/CustomToast.tsx
../../packages/ui/src/index.tsx
./tamagui.config.ts

../../node_modules/expo-constants/build/ExponentConstants.web.js
Attempted import error: 'uuidv4' is not exported from 'expo-modules-core' (imported as 'uuidv4').

Import trace for requested module:
../../node_modules/expo-constants/build/ExponentConstants.web.js
../../node_modules/expo-constants/build/Constants.js
../../packages/ui/src/CustomToast.tsx
../../packages/ui/src/index.tsx
./tamagui.config.ts

unhandledRejection TypeError: (0 , o.uuidv4) is not a function
    at 9370 (/home/ubuntu/top-fort-platform/apps/next/.next/server/chunks/5821.js:1:45603)
    at __webpack_require__ (/home/ubuntu/top-fort-platform/apps/next/.next/server/webpack-runtime.js:1:145)
    at /home/ubuntu/top-fort-platform/apps/next/.next/server/chunks/4098.js:1:147
    at __webpack_require__.a (/home/ubuntu/top-fort-platform/apps/next/.next/server/webpack-runtime.js:1:976)
    at 710 (/home/ubuntu/top-fort-platform/apps/next/.next/server/chunks/4098.js:1:82)
    at __webpack_require__ (/home/ubuntu/top-fort-platform/apps/next/.next/server/webpack-runtime.js:1:145)
    at /home/ubuntu/top-fort-platform/apps/next/.next/server/chunks/4098.js:1:3408
    at __webpack_require__.a (/home/ubuntu/top-fort-platform/apps/next/.next/server/webpack-runtime.js:1:976)
    at 19459 (/home/ubuntu/top-fort-platform/apps/next/.next/server/chunks/4098.js:1:3324)
    at __webpack_require__ (/home/ubuntu/top-fort-platform/apps/next/.next/server/webpack-runtime.js:1:145) {
  type: 'TypeError'
}
```

![builBugExpoConstants](https://github.com/Protofy-xyz/Protofy/assets/110179160/becf13ac-d069-4e7b-ba85-5c5092417049)

**Comment by noreplydev** [comment]
Share please the network windows /register request status by clicking on it, like this: 

![Screenshot 2024-02-05 at 12 52 20](https://github.com/Protofy-xyz/Protofy/assets/99766455/0e497467-9191-4cf7-9284-2f3f7004c154)

![Screenshot 2024-02-05 at 12 52 37](https://github.com/Protofy-xyz/Protofy/assets/99766455/0fb4637e-1377-489f-9518-e825ed9fa8c7)

Also, try login and register in both OS instead of sharing photos of each one in different environments.

**Comment by theG3n15** [comment]
I am getting the same error both in login and register. I will add detailed screenshots of one of the cases (Login / Register) as they behave exactly the same (the error for Login and Register in Windows, and same between pages in Ubuntu):

WINDOWS 11
- LOGIN
![Captura de pantalla 2024-02-05 124555](https://github.com/Protofy-xyz/Protofy/assets/110179160/08440092-adf3-48c6-b077-2c9fba425b2d)
![windowsLogin](https://github.com/Protofy-xyz/Protofy/assets/110179160/2198eeed-1982-429e-aeee-3c19b98de221)
![windowsLoginResponse](https://github.com/Protofy-xyz/Protofy/assets/110179160/1f52fc96-cbb4-459f-b3df-fcb029c3a67a)

- REGISTER
![WindowsRegister](https://github.com/Protofy-xyz/Protofy/assets/110179160/6e8a0ac1-f324-4b9b-8559-e79bb3216249)


UBUNTU 22.04.03 LTS
- LOGIN
![UbuntuLogin](https://github.com/Protofy-xyz/Protofy/assets/110179160/b09e1eba-5ebb-4f3d-9ec7-51ebb33a547d)


- REGISTER
![Captura de pantalla 2024-02-05 124728](https://github.com/Protofy-xyz/Protofy/assets/110179160/49867f32-b2c4-4a39-9fbf-95f5db1f917a)
![ubuntuRegister](https://github.com/Protofy-xyz/Protofy/assets/110179160/094551aa-093a-4cdf-a14b-edb432ac1929)
![ubuntuRegisterResponse](https://github.com/Protofy-xyz/Protofy/assets/110179160/5a59517b-a385-4fca-a4fe-7e459b3f2081)

**Comment by gdomenech98** [comment]
Now its working, steps i've did:
1. Build your frontend: `yarn web:build`
<img width="755" alt="Screenshot 2024-03-28 at 16 19 52" src="https://github.com/Protofy-xyz/Protofy/assets/108338080/840cfa74-af28-426d-9e72-cb8da40d7fef">
2. Run your project in production: `yarn start-dev`
3. Login with already created user with type 'admin' at http://localhost:8000

https://github.com/Protofy-xyz/Protofy/assets/108338080/7bf1ffba-2e34-4a6e-b47e-3f5259e3fea6
